[#44] 투표 통계 뷰 refetch 이슈 수정
ryuni-dev/meezzle pull request #47
Opened 2023-01-18 15:18 UTC by KUcodemaster

> 작성자 : 신재훈
> 이  슈 :  [#44]
> 작성일: 2023.1.19  

# 종류
- [ ] 성능 개선
- [ ] 코드 개선
- [x] 버그 수정
- [ ] 기능 추가
- [ ] 기타

# 변경내용

* 통계보고 투표하고 통계볼 때 refetch를 하지 않아 통계에 반영이 안되는 오류 수정
* 통계 페이지 접속시 refetch하도록 만듦

2023-01-19 07:08 UTC, ryuni-dev requested changes
리뷰 달아놓은 것 검토해보시고 수정 부탁드립니다. 이견 있으시면 언제든 댓글 달아주세용

2023-01-19 07:08 UTC, ryuni-dev commented on meezzle-front/pages/event/[eid]/info.tsx
> -    const errorHandler = () => {
그냥 errorHandler 함수 자체는 놔두는게 나을거 같아요. 나중에 코드 보면 무슨 코드인지 알기 쉽게

2023-01-19 07:08 UTC, ryuni-dev commented on meezzle-front/utils/converter.tsx
> +                parseInt(`${Number(time[1].split(":")[1]) / 30}`) -
백틱을 사용하면 문자열로 바뀌는데 number로 바꿨다가 string으로 다시 바꾸고 그걸 다시 number로 바꿀 이유가 없습니다.
여기에선 parseInt()랑 Number()랑 둘다 같은 역할이라 둘 중 하나만 쓰면 되고 백틱 사용 안 해도 됩니당.

2023-01-19 07:08 UTC, ryuni-dev commented on meezzle-front/utils/converter.tsx
> +                parseInt(`${Number(time[0].split(":")[1]) / 30}`);
위에랑 마찬가지로 백틱 사용할 필요 없고 혹여나 time[0].split(":")[1]에 문자가 섞이면 Number() 함수론 NaN 값이 나오니 처음부터 parseInt 쓰면 될거 같아요

2023-01-19 07:08 UTC, ryuni-dev commented on meezzle-front/pages/event/[eid]/view.tsx
>      useEffect(() => {
여간 지워도 될거 같아요

2023-01-19 07:08 UTC, ryuni-dev commented on meezzle-front/pages/event/[eid]/view.tsx
> +    useEffect(() => {
90-99번 줄과 153-190번 줄 if-else 로직이 겹쳐서 하나의 useEffect () 안에서 처리할 수 있어보입니다.

2023-01-19 07:15 UTC, KUcodemaster commented on meezzle-front/utils/converter.tsx
> +                parseInt(`${Number(time[1].split(":")[1]) / 30}`) -
parseInt의 인자값이 string으로 정의되어 있어 typescript 오류 방지를 위해 백틱 문자열을 사용했습니다. Number는 소수를 포함하는 숫자형이고, parseInt는 정수형으로 변환하기 때문에 나눗셈의 몫을 구하기 위해 parseInt를 사용했습니당

2023-01-19 07:29 UTC, ryuni-dev commented on meezzle-front/utils/converter.tsx
> +                parseInt(`${Number(time[1].split(":")[1]) / 30}`) -
Math.floor(Number(time.split(':')[1])/30) 가 나을거 같아요
type 변환을 여러 번 하면 그만큼 오버헤드가 발생해서 최대한 줄이고 싶어서요

2023-01-19 07:30 UTC, ryuni-dev commented on meezzle-front/utils/converter.tsx
> +                parseInt(`${Number(time[1].split(":")[1]) / 30}`) -
불필요한 타입 변환 외에도 Math.floor()가 parseInt()보다 속도가 더 빠르다곤 합니다.

2023-01-20 00:21 UTC, ryuni-dev reviewed
Good :)

2023-01-20 00:21 UTC, merged